[package]
name = "compare_sequences"
version = "0.1.0"
authors = ["Brian Gene Zhou <bzhou@umd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
